# Generated by Django 4.2.7 on 2024-04-06 08:45

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GeneratePdf",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("field1", models.CharField(max_length=100)),
                ("field2", models.IntegerField()),
                ("field3", models.CharField(max_length=100)),
                ("field4", models.CharField(max_length=100)),
                ("field5", models.CharField(max_length=100)),
                ("field6", models.CharField(max_length=100)),
                ("field7", models.CharField(max_length=100)),
            ],
        ),
    ]
