# Generated by Django 4.2.7 on 2024-04-06 09:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billsystem2", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="signup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=100)),
                ("password", models.CharField(max_length=100)),
                ("cfm", models.CharField(max_length=100)),
            ],
        ),
    ]
