# Generated by Django 4.2.7 on 2024-04-06 10:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("billsystem2", "0003_rename_signup_signups"),
    ]

    operations = [
        migrations.DeleteModel(
            name="signups",
        ),
    ]
